'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,spawnSync}=require('node:child_process'),Database=require('better-sqlite3');
const source=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
assert.equal(fs.readFileSync(path.join(source,'.rehearsal-checkout'),'utf8').trim(),'synthetic-only-v1','Mark the isolated checkout, never a deployed directory');assert.ok(!fs.existsSync(path.join(source,'data/pottery.db')),'Refuse checkout containing application data');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'ql-rehearsal-'));
const secret=crypto.randomBytes(32).toString('hex'),password=crypto.randomBytes(24).toString('hex');
const env={PATH:process.env.PATH,NODE_ENV:'test',PORT:'0',JWT_SECRET:secret};
const tracked=spawnSync('git',['ls-files','-z'],{cwd:source,encoding:'utf8'});assert.equal(tracked.status,0);
const release=tracked.stdout.split('\0').filter(Boolean).filter(p=>!p.startsWith('data/')&&!/(^|\/)\.env(?:\.|$)|\.(pem|key)$/.test(p)&&!p.startsWith('.git/')&&!p.startsWith('ql/rehearsal/evidence/'));
function inside(p){assert.ok(path.resolve(p).startsWith(root+path.sep),'Only generated disposable paths allowed');}
function generation(name){const dir=path.join(root,name);inside(dir);fs.mkdirSync(dir,{recursive:false});for(const p of release){const out=path.join(dir,p);fs.mkdirSync(path.dirname(out),{recursive:true});fs.copyFileSync(path.join(source,p),out);}fs.cpSync(__dirname,path.join(dir,'ql/rehearsal'),{recursive:true,filter:p=>!p.includes(path.sep+'evidence')});fs.symlinkSync(path.join(source,'node_modules'),path.join(dir,'node_modules'));fs.writeFileSync(path.join(dir,'.rehearsal-disposable'),'v1');return dir;}
function open(dir,readonly=false){inside(dir);return new Database(path.join(dir,'data/pottery.db'),{readonly,fileMustExist:true});}
function state(dir){const db=open(dir,true);try{const objects=db.prepare('SELECT type,name,tbl_name,sql FROM sqlite_master ORDER BY type,name').all();const tables=objects.filter(x=>x.type==='table');return {objects,columns:Object.fromEntries(tables.map(x=>[x.name,db.prepare('PRAGMA table_info('+JSON.stringify(x.name)+')').all()])),user_version:db.pragma('user_version',{simple:true}),rows:Object.fromEntries(tables.map(x=>[x.name,db.prepare('SELECT * FROM '+JSON.stringify(x.name)).all().sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))])),integrity:db.pragma('integrity_check'),foreignKeys:db.pragma('foreign_key_check')};}finally{db.close();}}
function manifest(dir,paths){inside(dir);const out=[];function walk(p){const f=path.join(dir,p),s=fs.lstatSync(f);assert.ok(!s.isSymbolicLink(),'Manifest rejects symlink '+p);if(s.isDirectory()){out.push({path:p,type:'directory',mode:s.mode&511});for(const n of fs.readdirSync(f).sort())walk(path.join(p,n));}else{assert.ok(s.isFile(),'No special files');out.push({path:p,type:'file',mode:s.mode&511,size:s.size,sha256:sha(fs.readFileSync(f))});}}for(const p of paths)walk(p);return out.sort((a,b)=>a.path.localeCompare(b.path));}
function cold(dir){const db=open(dir);const cp=db.pragma('wal_checkpoint(TRUNCATE)')[0];assert.equal(cp.busy,0);db.close();for(const ext of ['-wal','-shm']){const f=path.join(dir,'data/pottery.db'+ext);if(fs.existsSync(f))assert.equal(fs.statSync(f).size,0,'Nonempty sidecar');}}
function capture(dir,name){cold(dir);const baseline=state(dir);assert.deepEqual(baseline.integrity,[{integrity_check:'ok'}]);assert.deepEqual(baseline.foreignKeys,[]);const paths=['data',...release];assert.ok(release.includes('public/shop/the-potters-mud-log.pdf'),'Original must be a tracked release asset');const m=manifest(dir,paths);const backup=path.join(root,name);fs.mkdirSync(backup);for(const p of paths){const out=path.join(backup,p);fs.mkdirSync(path.dirname(out),{recursive:true});fs.cpSync(path.join(dir,p),out,{recursive:true,preserveTimestamps:true});}assert.deepEqual(manifest(backup,paths),m);const evidence=path.join(source,'ql/rehearsal/evidence');fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(path.join(evidence,name+'-manifest.json'),JSON.stringify(m,null,2));fs.writeFileSync(path.join(evidence,name+'-baseline.json'),JSON.stringify(baseline,null,2));return {backup,paths,manifest:m,manifestHash:sha(JSON.stringify(m)),baseline};}
function restore(cap,name){assert.deepEqual(manifest(cap.backup,cap.paths),cap.manifest);const dir=generation(name);fs.mkdirSync(path.join(dir,'data'));for(const p of cap.paths){const out=path.join(dir,p);fs.mkdirSync(path.dirname(out),{recursive:true});fs.cpSync(path.join(cap.backup,p),out,{recursive:true,preserveTimestamps:true});}assert.deepEqual(manifest(dir,cap.paths),cap.manifest);assert.deepEqual(state(dir),cap.baseline);return dir;}
function gate(dir,cap){assert.deepEqual(manifest(dir,cap.paths),cap.manifest);assert.deepEqual(state(dir),cap.baseline);}
const pause=()=>new Promise(r=>setTimeout(r,50));
async function start(dir,override={}){inside(dir);fs.rmSync(path.join(dir,'.port'),{force:true});let log='';const child=spawn(process.execPath,['server.js'],{cwd:dir,env:{...env,NODE_OPTIONS:'--require ./ql/rehearsal/isolate.cjs',...override},stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>log+=x);child.stderr.on('data',x=>log+=x);const s={dir,child,get log(){return log;}};for(let i=0;i<600;i++){if(child.exitCode!==null)throw Error('startup failed '+log);if(fs.existsSync(path.join(dir,'.port'))&&/\[Startup\] (All .*photos already|Backfill complete:)/.test(log)){s.base='http://127.0.0.1:'+fs.readFileSync(path.join(dir,'.port'),'utf8');return s;}await pause();}child.kill();throw Error('startup did not settle '+log);}
async function stop(s){if(s.child.exitCode===null){const done=new Promise(r=>s.child.once('exit',r));s.child.kill('SIGTERM');await done;}cold(s.dir);assert.ok(!fs.existsSync(path.join(s.dir,'.outbound-denied')),'Application attempted outbound traffic');}
async function request(s,url,token,options={}){assert.ok(url.startsWith('/'));const r=await fetch(s.base+url,{redirect:'manual',...options,headers:{...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});const bytes=Buffer.from(await r.arrayBuffer());let data;try{data=JSON.parse(bytes);}catch{data=bytes.toString();}return {status:r.status,headers:r.headers,bytes,data};}
async function login(s,email){const r=await request(s,'/api/auth/login',null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});assert.equal(r.status,200,JSON.stringify(r.data));return r.data.token;}
function diff(a,b){const out=[];function walk(x,y,p){if(JSON.stringify(x)===JSON.stringify(y))return;if(x&&y&&typeof x==='object'&&typeof y==='object'&&!Array.isArray(x)&&!Array.isArray(y)){for(const k of new Set([...Object.keys(x),...Object.keys(y)]))walk(x[k],y[k],p.concat(k));}else out.push({path:p.join('.'),before:x,after:y});}walk(a,b,[]);return out;}
module.exports={fs,path,assert,Database,source,root,release,sha,secret,password,env,generation,open,state,manifest,cold,capture,restore,gate,start,stop,request,login,diff,spawnSync};
