'use strict';
const c=require('./core.cjs'),f=require('./fixture.cjs'),jwt=require('jsonwebtoken');
const {fs,path,assert,root,open,state,restore,request,login}=c;
module.exports=async function extended({cap,boot,halt,check,report}){
 const dir=restore(cap,'entitlements'),s=await boot(dir),db=open(dir);const matrix=[];
 for(const tier of ['free','starter','basic','mid','top','promo',null,'unknown'])await check('entitlement matrix '+tier,async()=>{
 const id=tier===null?'null':tier==='unknown'?'free':tier;
 db.pragma('ignore_check_constraints=ON');db.prepare('UPDATE users SET tier=? WHERE id=?').run(tier==='promo'?'starter':tier,id);db.pragma('ignore_check_constraints=OFF');const token=await login(s,id+'@example.invalid');const qualified=['starter','basic','mid','top','promo'].includes(tier),expect=qualified?200:403;
 const routes=['/api/test-tiles','/api/test-tiles/ent-tile-'+id,'/api/ql/test-tiles/ent-tile-'+id+'/photos/1','/api/ql/pieces/ent-piece-'+id+'/test-tiles'];
 for(const route of routes)assert.equal((await request(s,route,token)).status,expect,route);
 const post=await request(s,routes[3],token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({testTileId:'ent-tile-'+id})});assert.ok(qualified?[200,201].includes(post.status):post.status===403);
 const history=(await request(s,'/api/ql/pieces/ent-piece-'+id+'/history',token)).data;assert.equal(history.testTilesAccess,qualified?'available':'locked');assert.equal(history.testTiles.length,qualified?1:0);if(!qualified)assert.ok(history.history.every(x=>x.recordType!=='test-tile'));matrix.push({tier,qualified,status:expect});if(tier==='unknown')db.prepare("UPDATE users SET tier='free' WHERE id='free'").run();
 });
 await check('missing account entitlement denied',async()=>{const token=jwt.sign({userId:'absent',tier:'starter'},c.secret);for(const route of ['/api/test-tiles','/api/test-tiles/tile-a','/api/ql/test-tiles/tile-a/photos/1'])assert.equal((await request(s,route,token)).status,403);});db.close();await halt(s);
 const again=await boot(dir);const normalized=state(dir);await check('full startup normalization retains qualifying effective access',async()=>{for(const tier of ['basic','mid','top']){assert.equal(normalized.rows.users.find(x=>x.id===tier).tier,'starter');const token=await login(again,tier+'@example.invalid');for(const url of ['/api/test-tiles','/api/test-tiles/ent-tile-'+tier,'/api/ql/test-tiles/ent-tile-'+tier+'/photos/1','/api/ql/pieces/ent-piece-'+tier+'/test-tiles'])assert.equal((await request(again,url,token)).status,200);assert.equal((await request(again,'/api/ql/pieces/ent-piece-'+tier+'/history',token)).data.testTilesAccess,'available');}});await halt(again);report.entitlementMatrix=matrix;
 await check('separate secret rotation rejects old JWT and permits new login',async()=>{const d=restore(cap,'secret-rotation'),old=jwt.sign({userId:'a'},c.secret),rotated=await boot(d,{JWT_SECRET:require('crypto').randomBytes(32).toString('hex')});assert.equal((await request(rotated,'/api/pieces',old)).status,401);assert.equal((await request(rotated,'/api/pieces',await login(rotated,'a@example.invalid'))).status,200);await halt(rotated);});
 await check('Forum block unblock private merchant and Contact update on separate copy',async()=>{const d=restore(cap,'mutable-api'),server=await boot(d),a=await login(server,'a@example.invalid'),b=await login(server,'b@example.invalid'),db=open(d);
 for(const [who,whom]of [['a','b'],['b','a']]){db.prepare('INSERT INTO blocked_users(id,user_id,blocked_user_id) VALUES(?,?,?)').run('synthetic-block',who,whom);assert.equal((await request(server,'/api/ql/forum/posts/post-a/media/forum-image',b)).status,404);db.exec("DELETE FROM blocked_users WHERE id='synthetic-block'");assert.equal((await request(server,'/api/ql/forum/posts/post-a/media/forum-image',b)).status,200);}
 db.prepare("UPDATE users SET email='christinaworkmanpottery@gmail.com' WHERE id='admin'").run();const admin=await login(server,'christinaworkmanpottery@gmail.com');assert.equal((await request(server,'/api/ql/shop/products/inactive/image',admin)).status,200);assert.equal((await request(server,'/api/ql/shop/products/inactive/image',a)).status,404);db.prepare("UPDATE users SET email='admin@example.invalid' WHERE id='admin'").run();
 const body={name:'Updated contact',role:'buyer',address:'456 Synthetic Street',instagram:'@synthetic',website:'https://example.invalid/new'};const options={method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};assert.equal((await request(server,'/api/contacts/contact-a',a,options)).status,200);const contact=(await request(server,'/api/contacts/contact-a',a)).data;for(const [key,value]of Object.entries(body))assert.equal(contact[key],value);const created=await request(server,'/api/contacts',a,{...options,method:'POST'});assert.equal(created.status,200);assert.equal((await request(server,'/api/contacts/'+created.data.id,a)).data.address,body.address);
 db.exec("UPDATE events SET contact_id='missing-contact' WHERE id='event-unlinked'");assert.equal((await request(server,'/api/contacts/missing-contact',a)).status,404);assert.equal(db.prepare("SELECT contact_id FROM events WHERE id='event-unlinked'").get().contact_id,'missing-contact');db.close();await halt(server);});
 const cases=[
 ['interrupted-restore',d=>fs.rmSync(path.join(d,'data/pottery.db'))],
 ['corrupt-db',d=>fs.writeFileSync(path.join(d,'data/pottery.db'),'CORRUPT synthetic')],
 ['missing-media-subset',d=>fs.unlinkSync(path.join(d,'data/uploads/piece-a.jpg'))],
 ['empty-media',d=>{fs.rmSync(path.join(d,'data/uploads'),{recursive:true});fs.mkdirSync(path.join(d,'data/uploads'));}],
 ['orphan-media',d=>fs.copyFileSync(path.join(d,'data/uploads/piece-a.jpg'),path.join(d,'data/uploads/orphan.jpg'))],
 ['wrong-owner-filename',d=>sql(d,"UPDATE piece_photos SET filename='piece-a.jpg' WHERE id='piece-photo-b'")],
 ['dangling-relationship',d=>sql(d,"UPDATE events SET contact_id='missing' WHERE id='event-a'")],
 ['wrong-owner-contact',d=>sql(d,"UPDATE sales SET contact_id='contact-b' WHERE id='sale-a'")],
 ['missing-ql-table',d=>sql(d,'DROP TABLE ql_piece_pricing')],
 ['missing-trigger',d=>sql(d,'DROP TRIGGER ql_piece_pricing_update')],
 ['ledger-drift',d=>sql(d,"UPDATE ql_migrations SET checksum='synthetic-drift'")],
 ['unreadable-media',d=>fs.chmodSync(path.join(d,'data/uploads/piece-a.jpg'),0)],
 ['unwritable-db',d=>fs.chmodSync(path.join(d,'data/pottery.db'),0o444)],
 ['unwritable-directory',d=>fs.chmodSync(path.join(d,'data'),0o555)],
 ['missing-release-asset',d=>fs.unlinkSync(path.join(d,'public/shop/the-potters-mud-log.pdf'))]
 ];
 const failures=[];for(const [name,inject]of cases)await check('failure copy '+name+' gate quarantine corrected restore',async()=>{const d=restore(cap,'failure-'+name);inject(d);assert.throws(()=>c.gate(d,cap));
 if(['missing-media-subset','orphan-media','wrong-owner-filename'].includes(name)){const diag=await boot(d),a=await login(diag,'a@example.invalid');if(name==='orphan-media'){assert.equal((await request(diag,'/api/ql/pieces/piece-a/photos/orphan',a)).status,404);assert.ok(fs.existsSync(path.join(d,'data/uploads/orphan.jpg')));}else{assert.equal((await request(diag,'/api/ql/pieces/piece-a/photos/piece-photo-a',a)).status,404);assert.ok(state(d).rows.piece_photos.some(x=>x.id==='piece-photo-a'));}await halt(diag);}
 if(['missing-ql-table','missing-trigger','ledger-drift'].includes(name)){const db=open(d);db.pragma('foreign_keys=ON');const before=state(d);assert.throws(()=>require('../relationships.cjs').migrate(db),/drift/);db.close();assert.deepEqual(state(d),before);}
 fs.renameSync(d,d+'-quarantine');const fixed=restore(cap,'corrected-'+name);c.gate(fixed,cap);const server=await boot(fixed);assert.deepEqual(state(fixed),cap.baseline);await halt(server);failures.push({name,manifestGate:'rejected',quarantine:'retained',correctedRestore:'PASS'});
 });report.failureInjection=failures;
 await check('nonroot permission failures preserve data',async()=>{fs.chmodSync(root,0o755);const d=restore(cap,'nonroot');for(const p of [d,path.join(d,'data'),path.join(d,'data/uploads')])fs.chmodSync(p,0o755);const media=path.join(d,'data/uploads/piece-a.jpg');fs.chmodSync(media,0);const probe=c.spawnSync(process.execPath,['-e',"const fs=require('fs');if(process.getuid()===0)process.exit(2);try{fs.readFileSync(process.argv[1]);process.exit(3)}catch(e){if(e.code!=='EACCES')throw e}" ,media],{...(process.getuid()===0?{uid:65534,gid:65534}:{}),env:{PATH:process.env.PATH},encoding:'utf8'});if(probe.error){const e=Error('Nonroot process unavailable locally: '+probe.error.code+'; must execute on nonroot CI runner');e.code='PERMISSION_RUNTIME_UNAVAILABLE';throw e;}assert.equal(probe.status,0,probe.stderr);const server=await boot(d);const token=await login(server,'a@example.invalid');assert.equal((await request(server,'/api/ql/pieces/piece-a/photos/piece-photo-a',token)).status,404);assert.ok(state(d).rows.piece_photos.some(x=>x.id==='piece-photo-a'));await halt(server);fs.chmodSync(media,0o644);const before=state(d);for(const target of ['db','directory']){fs.chmodSync(path.join(d,'data/pottery.db'),0o444);fs.chmodSync(path.join(d,'data'),0o555);const args=target==='db'?["const D=require(process.argv[2]);try{const d=new D(process.argv[1],{fileMustExist:true});d.prepare(\"UPDATE users SET bio='forbidden'\").run();process.exit(3)}catch(e){if(!/readonly|CANTOPEN|EACCES/.test(e.message+' '+e.code))throw e}",path.join(d,'data/pottery.db'),require.resolve('better-sqlite3')]:["const fs=require('fs');try{fs.writeFileSync(process.argv[1],'x');process.exit(3)}catch(e){if(e.code!=='EACCES')throw e}",path.join(d,'data/new-file')];const result=c.spawnSync(process.execPath,['-e',...args],{...(process.getuid()===0?{uid:65534,gid:65534}:{}),env:{PATH:process.env.PATH},encoding:'utf8'});assert.equal(result.status,0,result.stderr);}fs.chmodSync(path.join(d,'data/pottery.db'),0o644);fs.chmodSync(path.join(d,'data'),0o755);assert.deepEqual(state(d),before);const fixed=restore(cap,'nonroot-corrected');c.gate(fixed,cap);const recovered=await boot(fixed);assert.equal((await request(recovered,'/api/ql/pieces/piece-a/photos/piece-photo-a',await login(recovered,'a@example.invalid'))).status,200);await halt(recovered);});
 await check('source-specific account startup assignment is CHECK-safe and compatibility-preserving',async()=>{const d=restore(cap,'special-account');sql(d,"UPDATE users SET email='christinaworkmanpottery@gmail.com',tier='free',billing_period=NULL WHERE id='admin'");const server=await boot(d);const snap=state(d),account=snap.rows.users.find(x=>x.id==='admin');assert.equal(account.tier,'starter');assert.equal(account.billing_period,'monthly');const inspection=open(d);assert.deepEqual(inspection.pragma('integrity_check'),[{integrity_check:'ok'}]);inspection.close();const token=await login(server,'christinaworkmanpottery@gmail.com');const subscription=await request(server,'/api/user/subscription',token);assert.equal(subscription.status,200);assert.equal(subscription.data.status,'active');assert.equal(subscription.data.billingPeriod,'stripe-monthly');assert.equal(subscription.data.hasStripeSubscription,false);await halt(server);const again=await boot(d);const stable=state(d).rows.users.find(x=>x.id==='admin');assert.equal(stable.tier,'starter');assert.equal(stable.billing_period,'monthly');await halt(again);report.blockers.push({id:'admin-upgrade-billing-writers',detail:'Two existing Admin upgrade writers still default/write stripe-monthly with CHECK enforcement bypassed for accounts outside the three-account startup compatibility list. They remain a separate billing-integrity release blocker; this rehearsal does not repair them.'});});
};
function sql(dir,text){const db=open(dir);db.pragma('foreign_keys=OFF');try{db.exec(text);}finally{db.close();}}
