'use strict';
const c=require('./core.cjs'),{fs,path,assert,open,password,spawnSync}=c;
const bcrypt=require('bcryptjs'),sharp=require('sharp');
const stamp='2026-08-12 12:34:56';
function insert(db,table,row){const cols=Object.keys(row);db.prepare(`INSERT INTO ${table}(${cols.join(',')}) VALUES(${cols.map(()=>'?').join(',')})`).run(...Object.values(row));}
async function assets(dir){const up=path.join(dir,'data/uploads');fs.mkdirSync(up,{recursive:true});const jpg=await sharp({create:{width:32,height:32,channels:3,background:{r:30,g:80,b:180}}}).jpeg().toBuffer();const vid=path.join(up,'reply.mp4');const r=spawnSync('ffmpeg',['-loglevel','error','-f','lavfi','-i','color=c=blue:s=32x32:d=0.4','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',vid]);assert.equal(r.status,0,r.stderr?.toString());assert.equal(spawnSync('ffmpeg',['-v','error','-i',vid,'-f','null','-']).status,0);await require(path.join(dir,'generate-pdf.js')).generateMudLogPDF(path.join(dir,'public/shop/the-potters-mud-log.pdf'));fs.copyFileSync(path.join(dir,'public/shop/the-potters-mud-log.pdf'),path.join(up,'original.pdf'));for(const pdf of ['public/shop/the-potters-mud-log.pdf','public/shop/mud-log-preview.pdf']){const info=spawnSync('pdfinfo',[path.join(dir,pdf)]);assert.equal(info.status,0,info.stderr?.toString());const output=path.join(dir,'.decoded-pdf');const decoded=spawnSync('pdftoppm',['-f','1','-singlefile','-scale-to','32','-png',path.join(dir,pdf),output]);assert.equal(decoded.status,0,decoded.stderr?.toString());assert.ok((await sharp(output+'.png').raw().toBuffer()).length>0);fs.unlinkSync(output+'.png');}return jpg;}
async function seed(dir){const jpg=await assets(dir),db=open(dir);const hash=bcrypt.hashSync(password,10);db.pragma('foreign_keys=ON');
for(const id of ['a','b','free','starter','basic','mid','top','promo','null','admin']){const tier=['a','b','admin'].includes(id)?'starter':id==='null'?null:id==='promo'?'free':id;insert(db,'users',{id,email:id+'@example.invalid',password_hash:hash,tier,referral_code:'REHEARSAL-'+id,unit_system:'metric',temp_unit:'celsius',stripe_customer_id:'synthetic-customer-'+id,stripe_subscription_id:'synthetic-subscription-'+id,created_at:stamp,billing_period:'monthly',stores_migrated:1});}
insert(db,'beta_signups',{email:'promo@example.invalid',name:'Synthetic promo'});
db.exec("UPDATE users SET referral_code=NULL,stores_migrated=0,shop_url='https://example.invalid/shop' WHERE id='a'");
for(const owner of ['a','b']){
 insert(db,'clay_bodies',{id:'clay-'+owner,user_id:owner,name:'Same Clay'});insert(db,'glazes',{id:'glaze-'+owner,user_id:owner,name:'Same Glaze'});
 insert(db,'glaze_chemicals',{id:'material-'+owner,user_id:owner,name:'Typed Silica',quantity:12.5,unit:'g'});insert(db,'glaze_ingredients',{id:'ingredient-'+owner,glaze_id:'glaze-'+owner,ingredient_name:'Typed Silica',amount:'10.25 g'});
 insert(db,'pieces',{id:'piece-'+owner,user_id:owner,title:'Same title',clay_body_id:'clay-'+owner,studio:'Historical typed Clay',created_at:stamp,updated_at:stamp});
 for(const [table,key,parent] of [['piece_photos','piece_id','piece'],['clay_photos','clay_id','clay'],['glaze_photos','glaze_id','glaze']])insert(db,table,{id:parent+'-photo-'+owner,[key]:parent+'-'+owner,filename:parent+'-'+owner+'.jpg'});
 insert(db,'test_tiles',{id:'tile-'+owner,user_id:owner,clay_body_id:'clay-'+owner,glaze_id:'glaze-'+owner,clay_name:'Historical Clay',glaze_name:'Historical Glaze',photo_filename:'tile-'+owner+'.jpg',photo_filename2:'tile-'+owner+'-2.jpg',photo_filename3:'tile-'+owner+'-3.jpg'});
 insert(db,'pricing_calculations',{id:'pricing-'+owner,user_id:owner,inputs_json:'{"hours":2,"rate":25}',result_json:'{"price":65.95}',photo_filename:'pricing-'+owner+'.jpg'});
 insert(db,'contacts',{id:'contact-'+owner,user_id:owner,name:'Synthetic Contact '+owner,role:'gallery',address:'123 Fictional Lane',instagram:'@example',website:'https://example.invalid',email:'contact-'+owner+'@example.invalid',notes:'Historical contact',created_at:stamp,updated_at:stamp});
 insert(db,'sales',{id:'sale-'+owner,user_id:owner,piece_id:'piece-'+owner,contact_id:'contact-'+owner,price:65.95,quantity:2,date:'2026-08-12',image_filename:'sale-'+owner+'.jpg',created_at:stamp});
 insert(db,'events',{id:'event-'+owner,user_id:owner,title:'Synthetic market',event_date:'2026-10-10',start_time:'09:15',end_time:'12:30',contact_id:'contact-'+owner,image_filename:'event-'+owner+'.jpg',created_at:stamp,updated_at:stamp});
 insert(db,'firing_logs',{id:'firing-'+owner,user_id:owner,piece_id:'piece-'+owner,notes:'Legacy only'});insert(db,'firing_photos',{id:'firing-photo-'+owner,firing_id:'firing-'+owner,filename:'firing-'+owner+'.jpg'});
}
for(const [id,clay,text,pub]of [['manual',null,'Same Clay',0],['saved','clay-a',null,0],['public',null,null,1]])insert(db,'pieces',{id,user_id:'a',title:id,clay_body_id:clay,studio:text,is_public:pub,status:'done',created_at:stamp,updated_at:stamp});
insert(db,'piece_photos',{id:'public-photo',piece_id:'public',filename:'public.jpg',stage:'finished'});
for(const [id,g,n,order,method,coats] of [['layer-1','glaze-a',null,0,'dip',2],['layer-2',null,'Manual Same Glaze',1,'other',3],['layer-3','glaze-a',null,2,'brush',1],['layer-4','glaze-a','Historical custom',7,'pour',4],['layer-5',null,'Sparse historical',null,null,null]])insert(db,'piece_glazes',{id,piece_id:'piece-a',glaze_id:g,custom_name:n,layer_order:order,application_method:method,coats,notes:'Distinct '+id});
insert(db,'glaze_clay_tests',{id:'test-a',glaze_id:'glaze-a',clay_body_id:'clay-a',clay_name:'Historical test Clay',photo_filename:'test-a.jpg'});
for(const id of ['ql-only','matching','unlinked'])insert(db,'firing_logs',{id,user_id:'a',piece_id:id==='matching'?'piece-a':null,notes:id});
for(const [id,piece]of [['sale-second','piece-a'],['sale-unattached',null]])insert(db,'sales',{id,user_id:'a',piece_id:piece,contact_id:'contact-a',price:31.95,quantity:3,date:'2026-09-15',created_at:stamp});
insert(db,'events',{id:'event-unlinked',user_id:'a',title:'Independent',event_date:'2026-11-03',start_time:'14:00',end_time:'15:30',created_at:stamp,updated_at:stamp});
insert(db,'projects',{id:'project-a',user_id:'a',title:'Project'});insert(db,'project_photos',{id:'project-photo-a',project_id:'project-a',filename:'project-a.jpg'});
for(const id of ['private','public'])insert(db,'glaze_combos',{id:'combo-'+id,user_id:'a',name:id,is_shared:id==='public'?1:0,photo_filename:'combo-'+id+'.jpg',photo_filename2:'combo-'+id+'-2.jpg'});
db.exec("UPDATE users SET avatar_filename='avatar.jpg',profile_photo='profile.jpg' WHERE id='a'");
insert(db,'forum_posts',{id:'post-a',user_id:'a',title:'Synthetic post',body:'Body'});insert(db,'forum_posts',{id:'post-b',user_id:'b',title:'Other',body:'Body'});insert(db,'forum_replies',{id:'reply-b',post_id:'post-a',user_id:'b',body:'Reply'});insert(db,'forum_photos',{id:'forum-image',post_id:'post-a',filename:'forum.jpg'});insert(db,'forum_photos',{id:'forum-video',reply_id:'reply-b',filename:'reply.mp4'});
for(const [id,active,digital]of [['active',1,'original.pdf'],['inactive',0,null],['builtin',1,'the-potters-mud-log.pdf']])insert(db,'merchant_products',{id,name:id,price:12.95,product_type:'pdf',is_digital:1,is_active:active,image_filename:'shop-'+id+'.jpg',download_filename:digital});
for(const [id,owner,status,product]of [['completed','a','completed','active'],['pending','a','pending','active'],['second','b','completed','active'],['builtin','a','completed','builtin']])insert(db,'merchant_orders',{id,user_id:owner,product_id:product,price_paid:12.95,status,stripe_session_id:'synthetic-session-'+id,created_at:stamp});
const slots=require('../../deletion-lifecycle.cjs').fileSlots;for(const [table,columns]of Object.entries(slots))for(const row of db.prepare('SELECT * FROM '+table).all())for(const col of columns){const filename=row[col];if(filename&&!filename.endsWith('.pdf')&&!filename.endsWith('.mp4'))fs.writeFileSync(path.join(dir,'data/uploads',filename),jpg);}
for(const id of ['free','starter','basic','mid','top','promo','null']){insert(db,'pieces',{id:'ent-piece-'+id,user_id:id,title:'Entitlement'});insert(db,'test_tiles',{id:'ent-tile-'+id,user_id:id,photo_filename:'ent-'+id+'.jpg'});fs.writeFileSync(path.join(dir,'data/uploads','ent-'+id+'.jpg'),jpg);}
for(const f of fs.readdirSync(path.join(dir,'data/uploads')).filter(x=>x.endsWith('.jpg')))assert.equal((await sharp(path.join(dir,'data/uploads',f)).raw().toBuffer()).length,32*32*3);
db.close();return jpg;
}
function install(dir){const db=open(dir);db.pragma('foreign_keys=ON');const {migrate,link}=require('../relationships.cjs');assert.equal(migrate(db).applied,true);for(const [kind,id,pieces]of [['firing','ql-only',['piece-a']],['firing','matching',['piece-a']],['pricing','pricing-a',['piece-a','saved']],['testTile','tile-a',['piece-a','saved']]])for(const pieceId of pieces)link(db,{userId:'a',pieceId,kind,targetId:id});for(const tier of ['free','starter','basic','mid','top','promo','null'])link(db,{userId:tier,pieceId:'ent-piece-'+tier,kind:'testTile',targetId:'ent-tile-'+tier});db.close();}
module.exports={seed,assets,install,insert};
