'use strict';
const c=require('./core.cjs'),f=require('./fixture.cjs'),schema=require('../schema.json'),{createFixture}=require('../fixtures.cjs');
const {fs,path,assert,open,state,generation,capture,restore}=c;
module.exports=async function historical({boot,halt,check,report,fresh,currentCap}){
 const d=generation('historical');fs.mkdirSync(path.join(d,'data'));const db=new c.Database(path.join(d,'data/pottery.db'));
 const firing=schema.tables.find(x=>x.name==='firing_logs'),sales=schema.tables.find(x=>x.name==='sales');const saved=[firing.sql,sales.sql];
 try{firing.sql=firing.sql.replace("'lustre', ",'').replace("'lustre',",'');sales.sql=sales.sql.replace(/venue_type TEXT\s*,/,"venue_type TEXT CHECK(venue_type IN ('market','online','other')), ");createFixture(db,{legacy:true});}finally{[firing.sql,sales.sql]=saved;}
 const bcrypt=require('bcryptjs');db.prepare('UPDATE users SET password_hash=?,tier=?,billing_period=?,stores_migrated=1,referral_code=id').run(bcrypt.hashSync(c.password,10),'basic','monthly');
 db.exec("UPDATE pieces SET studio='Historical typed Clay' WHERE id='piece-a'; UPDATE piece_glazes SET coats=3,notes='Historical notes',application_method='other',layer_order=NULL WHERE id='layer-a'; INSERT INTO piece_glazes(id,piece_id,glaze_id,coats,notes,application_method,layer_order,custom_name) VALUES('historical-repeat','piece-a','glaze-a',2,'Repeated historical','brush',7,'Historical custom')");db.close();
 const jpg=await f.assets(d);const populate=open(d);for(const [table,cols]of Object.entries(require('../../deletion-lifecycle.cjs').fileSlots))for(const r of populate.prepare('SELECT * FROM '+table).all())for(const col of cols)if(r[col])fs.writeFileSync(path.join(d,'data/uploads',r[col]),jpg);populate.close();
 let cap;await check('historical exact offline restore before intentional startup',()=>{cap=capture(d,'historical-backup');report.manifests.historical=cap.manifestHash;restore(cap,'historical-restored');});
 const rd=path.join(c.root,'historical-restored'),before=state(rd),server=await boot(rd);await halt(server);const after=state(rd),freshState=state(fresh);
 await check('historical compatibility rebuilds and every startup delta classified',()=>{
 assert.deepEqual(after.integrity,[{integrity_check:'ok'}]);assert.deepEqual(after.foreignKeys,[]);assert.equal(after.user_version,before.user_version);
 const allowedRebuilds=['firing_logs','sales','test_tiles','piece_glazes'];const changes=[];
 for(const obj of before.objects){const next=after.objects.find(x=>x.name===obj.name&&x.type===obj.type);assert.ok(next,obj.name);if(JSON.stringify(next)!==JSON.stringify(obj)){assert.equal(obj.type,'table');assert.ok(allowedRebuilds.includes(obj.name),obj.name);changes.push({kind:'legacy-rebuild',table:obj.name,before:obj.sql,after:next.sql});}}
 for(const obj of after.objects.filter(x=>!before.objects.some(b=>b.name===x.name&&b.type===x.type))){const expected=freshState.objects.find(x=>x.type===obj.type&&x.name===obj.name);assert.ok(expected,'Unexpected object '+obj.name);assert.equal(obj.sql,expected.sql,'Unexpected DDL '+obj.name);changes.push({kind:'additive-schema',object:obj});}
 for(const [table,cols]of Object.entries(before.columns)){const expected=cols.map(x=>table==='piece_glazes'&&x.name==='glaze_id'?{...x,notnull:0}:x);assert.deepEqual(after.columns[table],expected,'column preservation '+table);}
 const seedTables=['forum_categories','admin_docs','blog_posts','email_sends','migrations'];
 for(const [table,rows]of Object.entries(before.rows)){if(seedTables.includes(table)){assert.equal(rows.length,0);const generated=after.rows[table],reference=freshState.rows[table];assert.equal(generated.length,reference.length,table);for(const r of generated){const key=table==='admin_docs'||table==='blog_posts'?'slug':table==='migrations'?'name':'id';const ref=reference.find(x=>x[key]===r[key]);assert.ok(ref,table+':'+r[key]);const dynamic=table==='admin_docs'?['id','created_at','updated_at']:table==='blog_posts'?['id','created_at','updated_at','published_at']:table==='migrations'?['applied_at']:[];for(const [k,v]of Object.entries(r))if(dynamic.includes(k)){assert.ok(v);if(k==='id'){if(ref[k].startsWith('blog-'))assert.equal(v,ref[k]);else assert.match(v,/^[0-9a-f-]{36}$/);}else assert.match(v,/^\d{4}-\d\d-\d\d/);}else assert.deepEqual(v,ref[k],table+'.'+k);}changes.push({kind:'source-seeding',table,count:generated.length});continue;}
 const newer=after.rows[table];assert.equal(newer.length,rows.length,table);for(const row of rows){const next=newer.find(x=>x.id===row.id);assert.ok(next);if(table==='users'){assert.deepEqual({...next,tier:row.tier},row);assert.equal(next.tier,'starter');changes.push({kind:'tier-normalization',id:row.id,from:row.tier,to:next.tier});}else if(table==='piece_photos'){assert.deepEqual({...next,phash:row.phash,avg_color:row.avg_color},row);assert.ok(next.phash&&next.avg_color);changes.push({kind:'photo-signature',id:row.id});}else assert.deepEqual(next,row,table+':'+row.id);}}
 assert.deepEqual(c.manifest(rd,['data/uploads']),c.manifest(d,['data/uploads']));report.diffs.historical=changes;
 });
 await check('historical stable restart then existing migrate helper only',async()=>{const stable=state(rd),s=await boot(rd);await halt(s);assert.deepEqual(state(rd),stable);const db=open(rd);db.pragma('foreign_keys=ON');assert.equal(require('../relationships.cjs').migrate(db).applied,true);db.close();const migrated=state(rd);for(let i=0;i<2;i++){const again=await boot(rd);await halt(again);assert.deepEqual(state(rd),migrated);}});
 for(const variant of ['firing_logs','sales','test_tiles','piece_glazes'])await check('guarded '+variant+' rebuild required after QL refuses without mutation',async()=>{
 const fail=restore(currentCap,'guarded-'+variant);const db=open(fail);const original=db.prepare('SELECT sql FROM sqlite_master WHERE name=?').get(variant).sql;let changed=original;
 if(variant==='firing_logs')changed=original.replace("'lustre', ",'').replace("'lustre',",'');
 if(variant==='sales')changed=original.replace(/venue_type TEXT\s*,/,"venue_type TEXT CHECK(venue_type IN ('market','online','other')), ");
 if(variant==='test_tiles')changed=original.replace("'underglaze', ",'').replace("'underglaze',",'');
 if(variant==='piece_glazes')changed=original.replace('glaze_id TEXT,','glaze_id TEXT NOT NULL,');
 assert.notEqual(changed,original);db.unsafeMode(true);db.pragma('writable_schema=ON');db.prepare('UPDATE sqlite_master SET sql=? WHERE name=?').run(changed,variant);db.pragma('writable_schema=OFF');db.pragma('schema_version='+(db.pragma('schema_version',{simple:true})+1));db.close();const before=state(fail);const run=c.spawnSync(process.execPath,['server.js'],{cwd:fail,env:{...c.env,NODE_OPTIONS:'--require ./ql/rehearsal/isolate.cjs'},encoding:'utf8',timeout:10000});assert.notEqual(run.status,0);assert.match(run.stderr,/startup rejected without mutation/);assert.deepEqual(state(fail),before);
 });
};
