'use strict';
const c=require('./core.cjs'),f=require('./fixture.cjs');
const {fs,path,assert,root,source,sha,generation,open,state,capture,restore,start,stop,request,login,diff}=c;
const jwt=require('jsonwebtoken');
const report={version:1,fixtureVersion:1,sourceCheckpoint:'4f570ec1c3d63f2fc35be94ca7f2f5f4bc532d0a',commit:c.spawnSync('git',['rev-parse','HEAD'],{cwd:source,encoding:'utf8'}).stdout.trim(),runtime:{node:process.version,sqlite:new c.Database(':memory:').prepare('select sqlite_version() v').get().v},checks:[],diffs:{},manifests:{},blockers:[{id:'admin-demographics',detail:'Source queries users.is_admin; fresh schema lacks it. Separate isAdmin(req) authorization maintenance required.'},{id:'missing-release-shop-original',detail:'Tracked source lacks public/shop/the-potters-mud-log.pdf; a disposable generated PDF exercises binding, not release artifact availability.'}],limitations:['Global /uploads remains unrestricted.','JWT signature/expiry controls validity; logout/restart/replacement login do not universally revoke JWTs.','Client guards do not constitute server token revocation.','Forum playback grants are memory-only and reset on restart.','Startup normalizes basic/mid/top to starter and synchronizes beta access.','Some source initialization errors are swallowed.','No recovery generation marker or create idempotency guarantee: valid same-account stale queued operations may replay after rollback.','Server backup excludes mobile SQLite, AsyncStorage and device queues.','Production infrastructure snapshot consistency, retention, restore behavior, capacity, contents and non-disk assets remain unknown.'],verification:{backend:{expectedExistingCount:1314,command:'node --require ./ql/rehearsal/suite-isolate.cjs ql/verify-phase1.cjs'},strictPhase1:37,mobileQueue:{source:'7ab57c662daa2c8d97cfbd9a3cc454bbe2cd1a8e',tests:64,result:'PASS local; reused source/tests match checkpoint blobs; mobile unchanged'},editorPreservation:95,initialization:53},productionAccess:false,phase3:'closed'};
const active=new Set();
async function boot(dir,overrides){const s=await start(dir,overrides);active.add(s);return s;}
async function halt(s){await stop(s);active.delete(s);}
async function check(name,fn){const begin=Date.now();try{await fn();report.checks.push({name,result:'PASS',ms:Date.now()-begin});console.log('PASS '+name);}catch(e){report.checks.push({name,result:e.code==='PERMISSION_RUNTIME_UNAVAILABLE'?'BLOCKED':'FAIL',error:e.message});if(e.code==='PERMISSION_RUNTIME_UNAVAILABLE'){console.log('BLOCKED '+name+': '+e.message);return;}throw e;}}
function rowChanges(before,after){const changes=[];for(const table of new Set([...Object.keys(before.rows),...Object.keys(after.rows)])){const a=before.rows[table]||[],b=after.rows[table]||[];const key=r=>r.id??r.name??JSON.stringify(r);const am=new Map(a.map(r=>[key(r),r])),bm=new Map(b.map(r=>[key(r),r]));for(const id of new Set([...am.keys(),...bm.keys()]))if(JSON.stringify(am.get(id))!==JSON.stringify(bm.get(id)))changes.push({table,id,before:am.get(id),after:bm.get(id)});}return changes;}
function startupDelta(before,after,label){assert.deepEqual(after.objects,before.objects,'Unexpected schema drift');assert.deepEqual(after.columns,before.columns);assert.equal(after.user_version,before.user_version);assert.deepEqual(after.integrity,[{integrity_check:'ok'}]);assert.deepEqual(after.foreignKeys,[]);const changes=rowChanges(before,after);for(const x of changes){if(x.table==='users'&&x.before&&x.after){const fields=Object.keys(x.before).filter(k=>JSON.stringify(x.before[k])!==JSON.stringify(x.after[k]));for(const k of fields){if(k==='tier'){assert.ok(['basic','mid','top'].includes(x.before[k])||x.id==='promo');assert.equal(x.after[k],'starter');}else if(k==='stores_migrated')assert.equal(x.after[k],1);else if(k==='referral_code'){assert.equal(x.before[k],null);assert.match(x.after[k],/^[A-Z0-9]+$/);}else if(k==='billing_period'&&x.id==='admin')assert.equal(x.after[k],'stripe-monthly');else if(['billing_period','plan_expires_at','is_beta_tester'].includes(k)&&x.id==='promo')assert.equal(x.after[k],{billing_period:'promo',plan_expires_at:null,is_beta_tester:1}[k]);else assert.fail('Unclassified users mutation '+x.id+'.'+k);}}else if(x.table==='piece_photos'&&x.before&&x.after){for(const k of Object.keys(x.before))if(!['phash','avg_color'].includes(k))assert.deepEqual(x.after[k],x.before[k]);assert.ok(x.after.phash&&x.after.avg_color);JSON.parse(x.after.avg_color);}else if(x.table==='user_stores'&&!x.before){assert.equal(x.after.user_id,'a');assert.equal(x.after.url,'https://example.invalid/shop');assert.match(x.after.created_at,/^\d{4}-\d\d-\d\d /);assert.equal(x.after.sort_order,0);assert.match(x.after.id,/^[0-9a-f-]{36}$/);}else assert.fail('Unclassified startup mutation '+JSON.stringify(x));}report.diffs[label]=changes;return changes;}
function loginDelta(before,after,label){assert.deepEqual(after.objects,before.objects);const changes=rowChanges(before,after);for(const x of changes){assert.equal(x.table,'users');assert.ok(x.before&&x.after);assert.deepEqual({...x.after,last_login:x.before.last_login},x.before);assert.match(x.after.last_login,/^\d{4}-\d\d-\d\d /);}report.diffs[label]=changes;}
function relationshipAudit(dir){const db=open(dir,true);try{const audit=require('../integrity-audit.cjs').auditRelationships(db,{fileInventory:[...fs.readdirSync(path.join(dir,'data/uploads')),...(fs.existsSync(path.join(dir,'public/shop/the-potters-mud-log.pdf'))?['the-potters-mud-log.pdf']:[])]});const extra=[];for(const table of ['events','sales'])for(const row of db.prepare(`SELECT s.id,s.user_id,s.contact_id,c.id found,c.user_id owner FROM ${table} s LEFT JOIN contacts c ON s.contact_id=c.id WHERE s.contact_id IS NOT NULL`).all())if(!row.found||row.user_id!==row.owner)extra.push({table,...row});assert.deepEqual(extra,[]);return {audit,legacyContacts:extra};}finally{db.close();}}
const normalizeIcal=s=>s.replace(/^DTSTAMP:.*$/gm,'DTSTAMP:<generated>');
async function verify(s,previous={}){const before=state(s.dir),a=await login(s,'a@example.invalid'),b=await login(s,'b@example.invalid');
 await check('auth '+(s.label||path.basename(s.dir))+' login account switching',async()=>{for(const [token,id]of [[a,'a'],[b,'b'],[a,'a']])assert.equal((await request(s,'/api/auth/me',token)).data.user.id,id);for(const token of ['bad.jwt',jwt.sign({userId:'a'},c.secret,{expiresIn:-1}),jwt.sign({userId:'a'},'synthetic-wrong-secret')])assert.equal((await request(s,'/api/pieces',token)).status,401);const again=await login(s,'a@example.invalid');assert.equal((await request(s,'/api/pieces',again)).status,200);assert.equal((await request(s,'/api/pieces',a)).status,200);if(previous.a)assert.equal((await request(s,'/api/pieces',previous.a)).status,200);});
 const cases=[['/api/ql/pieces/piece-a/photos/piece-photo-a','piece-a.jpg'],['/api/ql/clay-bodies/clay-a/photos/clay-photo-a','clay-a.jpg'],['/api/ql/glazes/glaze-a/photos/glaze-photo-a','glaze-a.jpg'],['/api/ql/glazes/glaze-a/clay-tests/test-a/photo','test-a.jpg'],...['1','2','3'].map((n,i)=>['/api/ql/test-tiles/tile-a/photos/'+n,'tile-a'+(i?'-'+n:'')+'.jpg']),['/api/ql/community/combos/combo-private/photos/1','combo-private.jpg'],['/api/ql/firing-logs/firing-a/photos/firing-photo-a','firing-a.jpg'],['/api/ql/pricing-calculations/pricing-a/photos/pricing-a.jpg','pricing-a.jpg'],['/api/ql/sales/sale-a/photos/sale-a.jpg','sale-a.jpg'],['/api/ql/projects/project-a/photos/project-photo-a','project-a.jpg'],['/api/ql/events/event-a/photos/event-a.jpg','event-a.jpg'],['/api/ql/profiles/a/photos/avatar.jpg','avatar.jpg'],['/api/ql/profiles/a/photos/profile.jpg','profile.jpg']];
 for(const [url,file]of cases)await check((s.label||path.basename(s.dir))+' media '+file,async()=>{const ok=await request(s,url,a);assert.equal(ok.status,200,url+' '+JSON.stringify(ok.data));assert.deepEqual(ok.bytes,fs.readFileSync(path.join(s.dir,'data/uploads',file)));assert.ok([401,403,404].includes((await request(s,url)).status));assert.ok([403,404].includes((await request(s,url,b)).status));assert.ok([403,404].includes((await request(s,url.replace(/[^/]+$/,'wrong'),a)).status));});
 await check((s.label||path.basename(s.dir))+' public/community media contracts',async()=>{for(const url of ['/api/ql/pieces/public/photos/public-photo/public','/api/ql/community/combos/combo-public/photos/1/public','/api/ql/community/combos/combo-public/photos/2/public'])assert.equal((await request(s,url)).status,200);assert.equal((await request(s,'/api/ql/pieces/piece-a/photos/piece-photo-a/public')).status,404);assert.equal((await request(s,'/uploads/piece-a.jpg')).status,200);assert.equal((await request(s,'/api/ql/avatars/community/avatar.jpg',b)).status,200);});
 await check((s.label||path.basename(s.dir))+' relationships History and iCal',async()=>{for(const endpoint of ['history','firings','pricing','test-tiles']){const r=await request(s,'/api/ql/pieces/piece-a/'+endpoint,a);assert.equal(r.status,200,endpoint+JSON.stringify(r.data));if(previous[endpoint])assert.deepEqual(r.data,previous[endpoint]);previous[endpoint]=r.data;}assert.equal(previous.history.glazeLayers.length,5);assert.equal(previous.history.sales.length,2);assert.equal(previous.history.pricing.length,1);assert.equal(previous.history.testTiles.length,1);const savedLayers=previous.history.glazeLayers.filter(x=>x.values.layer.glaze_id==='glaze-a');assert.equal(savedLayers.length,3);for(const layer of previous.history.glazeLayers)assert.ok(layer.values.layer.notes.startsWith('Distinct '));const firings=previous.firings;assert.equal((Array.isArray(firings)?firings:firings.firings).filter(x=>x.id==='matching').length,1);for(const url of ['/api/events/export/ics','/api/events/subscribe/a']){const r=await request(s,url,a);assert.equal(r.status,200);const value=normalizeIcal(r.data);assert.match(value,/DTSTART:20261010T091500/);if(previous[url])assert.equal(value,previous[url]);previous[url]=value;}const d=(await request(s,'/api/contacts/contact-a',a));assert.equal(d.status,200);assert.equal(d.data.role,'gallery');assert.ok(d.data.events.some(x=>x.id==='event-a'));assert.ok(d.data.sales.some(x=>x.id==='sale-a'));assert.equal((await request(s,'/api/contacts/contact-a',b)).status,404);});
 await check((s.label||path.basename(s.dir))+' Forum image video HEAD ranges binding grants',async()=>{const image='/api/ql/forum/posts/post-a/media/forum-image',video='/api/ql/forum/posts/post-a/replies/reply-b/media/forum-video';for(const url of [image,video]){const r=await request(s,url,a);assert.equal(r.status,200,url);assert.equal((await request(s,url)).status,401);}const bytes=fs.readFileSync(path.join(s.dir,'data/uploads/reply.mp4'));assert.deepEqual((await request(s,video,a)).bytes,bytes);const head=await request(s,video,a,{method:'HEAD'});assert.equal(head.status,200);assert.equal(head.bytes.length,0);const range=await request(s,video,a,{headers:{Range:'bytes=0-15'}});assert.equal(range.status,206);assert.deepEqual(range.bytes,bytes.subarray(0,16));assert.equal((await request(s,video.replace('post-a','post-b'),a)).status,404);if(previous.stream)assert.equal((await request(s,previous.stream,null,{headers:{Cookie:previous.cookie}})).status,401);const nonce='rehearsal-'+require('crypto').randomBytes(16).toString('hex');const grant=await request(s,'/api/ql/forum/sessions/'+nonce,a,{method:'POST'});assert.equal(grant.status,200);previous.cookie=grant.headers.get('set-cookie').split(';')[0];previous.stream='/api/ql/forum/streams/'+nonce+'/posts/post-a/replies/reply-b/media/forum-video';assert.equal((await request(s,previous.stream,null,{headers:{Cookie:previous.cookie}})).status,200);});
 await check((s.label||path.basename(s.dir))+' Shop assets and purchaser isolation',async()=>{assert.equal((await request(s,'/api/ql/shop/products/active/image/public')).status,200);assert.equal((await request(s,'/api/ql/shop/products/inactive/image/public')).status,404);for(const [id,token,status]of [['completed',a,200],['pending',a,404],['completed',b,404],['second',b,200],['second',a,404],['builtin',a,200]]){const r=await request(s,'/api/shop/download/'+id,token);assert.equal(r.status,status,id);if(status===200)assert.deepEqual(r.bytes,fs.readFileSync(path.join(s.dir,id==='builtin'?'public/shop/the-potters-mud-log.pdf':'data/uploads/original.pdf')));}assert.equal((await request(s,'/shop/mud-log-preview.pdf')).status,200);assert.equal((await request(s,'/shop/the-potters-mud-log.pdf')).status,404);});
 await check((s.label||path.basename(s.dir))+' actual HTTP browser Clay Glaze read-only and late response guards',()=>require('./browser.cjs')(s,a,b));
 loginDelta(before,state(s.dir),'verification-'+(s.label||path.basename(s.dir)));previous.a=a;return previous;
}
async function main(){await check('outbound isolation positive probes',()=>{const d=generation('isolation-probe');const r=c.spawnSync(process.execPath,['-e',"require('./ql/rehearsal/isolate.cjs');for(const f of [()=>require('net').connect(443,'example.invalid'),()=>require('tls').connect(443,'example.invalid'),()=>fetch('https://example.invalid'),()=>require('dns').lookup('example.invalid'),()=>require('dgram').createSocket('udp4'),()=>require('child_process').spawn('true')]){try{f();throw Error('NOT BLOCKED')}catch(e){if(!e.message.startsWith('REHEARSAL_OUTBOUND_DENIED'))throw e}}"],{cwd:d,env:c.env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(fs.readFileSync(path.join(d,'.outbound-denied'),'utf8').trim().split('\n').length,6);});assert.match(process.version,/^v22\./);let fresh;
 await check('genuine empty first startup, schema, seeds, registration, login and reads',async()=>{fresh=generation('fresh');assert.ok(!fs.existsSync(path.join(fresh,'data')));const s=await boot(fresh);const snap=state(fresh);for(const table of require('../schema.json').tables)assert.deepEqual(snap.columns[table.name],table.columns,table.name);for(const [table,cols]of [['events',['contact_id']],['contacts',['role','address','instagram','website']]])for(const col of cols)assert.ok(snap.columns[table].some(x=>x.name===col));for(const [table,count]of Object.entries({forum_categories:13,admin_docs:3,blog_posts:6,email_sends:1,migrations:7}))assert.equal(snap.rows[table].length,count,table);assert.ok(fs.statSync(path.join(fresh,'data/uploads')).isDirectory());const r=await request(s,'/api/auth/register',null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'fresh@example.invalid',password:c.password,newsletterSubscribed:false})});assert.equal(r.status,200);const token=await login(s,'fresh@example.invalid');for(const url of ['/api/pieces','/api/contacts','/api/events'])assert.equal((await request(s,url,token)).status,200);const bad=await request(s,'/api/admin/demographics',token);assert.equal(bad.status,500);assert.match(s.log,/no such column: is_admin/);await halt(s);});
 await check('fresh restart classified and second startup stable',async()=>{const before=state(fresh);let s=await boot(fresh);await halt(s);startupDelta(before,state(fresh),'fresh-restart');const stable=state(fresh);s=await boot(fresh);await halt(s);assert.deepEqual(state(fresh),stable);});
 // Seed only after real current legacy initialization. Never apply QL to an unrepaired historical schema.
 const current=generation('current');let s=await boot(current);await halt(s);await check('representative decodable synthetic fixture',()=>f.seed(current));f.install(current);
 const pre=state(current);s=await boot(current);await halt(s);await check('explicit current startup mutation classification',()=>startupDelta(pre,state(current),'current-first'));
 await check('clean relationship Contact audit',()=>{report.relationshipAudit=relationshipAudit(current);assert.deepEqual(report.relationshipAudit.audit.issues,[]);});
 let cap;await check('cold paired backup checkpoint manifests exact offline restore',()=>{cap=capture(current,'backup');report.manifests.current=cap.manifestHash;const restored=restore(cap,'restored-0');report.offlineRestore={databaseBytes:'exact',schemaRowsRelationships:'exact',mediaPathsBytesPermissions:'exact',integrity:cap.baseline.integrity,foreignKeys:cap.baseline.foreignKeys};report.restored=path.basename(restored);});
 const restored=path.join(root,'restored-0');let previous={};for(let i=0;i<3;i++){const before=state(restored);s=await boot(restored);await check('restored startup '+i+' stable before login',()=>{assert.deepEqual(state(restored),before);});s.label='restored-cycle-'+i;previous=await verify(s,previous);await halt(s);assert.deepEqual(c.manifest(restored,['data/uploads']),c.manifest(cap.backup,['data/uploads']));}
 await require('./historical.cjs')({boot,halt,check,report,fresh,currentCap:cap});
 await require('./extended.cjs')({cap,boot,halt,check,report});
 report.final='BLOCKED';report.rehearsal=report.checks.every(x=>x.result==='PASS')?'PASS_WITH_SOURCE_BLOCKERS':'BLOCKED';report.counts={passed:report.checks.filter(x=>x.result==='PASS').length,failed:report.checks.filter(x=>x.result==='FAIL').length,blocked:report.checks.filter(x=>x.result==='BLOCKED').length,cancellations:0,skips:0,todos:0};if(report.counts.blocked)process.exitCode=1;
}
async function run(){try{await main();}catch(e){report.final='BLOCKED';report.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{for(const s of active)try{await halt(s);}catch{}const out=path.join(source,'ql/rehearsal/evidence');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'report.md'),'# Disposable recovery rehearsal\n\nStatus: '+report.final+'\n\n'+report.checks.map(x=>'- '+x.result+': '+x.name).join('\n')+'\n\n'+(report.error?'Execution stopped: '+report.error+'\n':'')+'\nKnown blockers:\n'+report.blockers.map(x=>'- '+x.detail).join('\n')+'\n\nKnown limitations:\n'+report.limitations.map(x=>'- '+x).join('\n')+'\n\nSource checkpoint: '+report.sourceCheckpoint+'\nTooling commit: '+report.commit+'\nRuntime: '+JSON.stringify(report.runtime)+'\nCounts: '+JSON.stringify(report.counts)+'\n\nSee report.json for exact startup/login diffs, entitlement matrix, audit, failure copies and manifest hashes; paired baseline and manifest JSON files capture complete synthetic rows and schema. Phase 3 closed; production untouched.\n');console.log('Evidence: '+out);console.log('Disposable evidence retained at '+root);}}
if(require.main===module)run();module.exports={run,report};
