'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {generate,sha}=require('../photo-eval/fixtures.cjs'),{validate,summarize,gates}=require('../photo-eval/metrics.cjs'),rt=require('../photo-eval/runtime.cjs');
const corpus=path.join(__dirname,'../photo-eval/corpus'),out=path.join(__dirname,'evidence');
async function run(){const frozen=process.argv.includes('--verify-frozen')?JSON.parse(fs.readFileSync(path.join(out,'plain-results.json'))):null;fs.mkdirSync(out,{recursive:true});if(!fs.existsSync(path.join(corpus,'queries.json')))await generate(corpus);const manifest=JSON.parse(fs.readFileSync(path.join(corpus,'fixtures.json'))),queries=JSON.parse(fs.readFileSync(path.join(corpus,'queries.json')));validate(manifest,queries);for(const f of [...manifest.references,...queries])assert.equal(sha(fs.readFileSync(path.join(corpus,f.file))),f.sha256,f.file);const data=q=>fs.readFileSync(path.join(corpus,q.file));const save=(name,v)=>fs.writeFileSync(path.join(out,name),JSON.stringify(v,null,2)+'\n');
 const all={cold:[],warm:[],repeat:[],plain:[]},progression=[],multi=[];let s;try{s=await rt.start(true);rt.seed(s,corpus,manifest);
 // Every cold query starts at the SAME empty feature state, with settled startup.
 // Cold shards use independent disposable servers/databases; EVERY request resets
 // all A feature pairs. Query bytes, labels, observation and ranking math are unchanged.
 // Cold latency includes four-way test load and is not a release latency measurement.
 await Promise.all(Array.from({length:4},async(_,shard)=>{let coldServer;try{coldServer=await rt.start(true);rt.seed(coldServer,corpus,manifest);for(const [i,q] of queries.entries()){if(i%4!==shard)continue;coldServer.db.prepare("UPDATE piece_photos SET phash=NULL,avg_color=NULL WHERE piece_id IN (SELECT id FROM pieces WHERE user_id='A')").run();const r=await rt.query(coldServer,data(q));all.cold[i]={...q,...r,evaluatedPieces:r.trace?.evaluatedPieces||[]};if(i%100<4)console.log('cold',i);}}finally{if(coldServer)await rt.stop(coldServer);}}));
 s.db.prepare("UPDATE piece_photos SET phash=NULL,avg_color=NULL WHERE piece_id IN (SELECT id FROM pieces WHERE user_id='A')").run();const tail=queries.find(q=>q.id==='M08-duplicate');for(let i=0;i<15;i++){const r=await rt.query(s,data(tail));progression.push({request:i+1,evaluatedPhotos:r.trace.evaluatedPhotos.length,evaluatedPieces:r.trace.evaluatedPieces.length,correctEvaluated:r.trace.evaluatedPieces.includes('M08'),ranking:r.ranking,ms:r.ms});}
 assert.equal(s.db.prepare("SELECT count(*) n FROM piece_photos pp JOIN pieces p ON p.id=pp.piece_id WHERE p.user_id='A' AND (phash IS NULL OR avg_color IS NULL)").get().n,0);
 for(const mode of ['warm','repeat'])for(const [i,q]of queries.entries()){const r=await rt.query(s,data(q));all[mode].push({...q,...r,evaluatedPieces:r.trace?.evaluatedPieces||[]});if(mode==='warm'){for(const expected of q.expected){const winner=r.trace?.winners.find(w=>w.piece_id===expected);multi.push({query:q.id,piece:expected,winningPhoto:winner?.photo_id??null,score:winner?.score??null,correctPieceTop1:r.ranking[0]?.id===expected,firstDisplayedPhoto:r.firstPhotos.find(x=>x.id===expected)?.photo??null,matchingPhotoExposed:r.apiMatchedPhoto});}}if(i%100===0)console.log(mode,i);}
 // Prove matching B-owned duplicate data is real and independently retrievable.
 for(let i=0;i<15;i++)await rt.query(s,data(tail),'B');const b=await rt.query(s,data(tail),'B');assert.ok(b.ranking.length);save('account-isolation.json',{accountAPieces:48,accountBPieces:48,identicalBReferences:144,queriesChecked:queries.length*4,BControlResults:b.ranking.length,leaks:0,scope:'Candidate IDs and complete serialized API response; protected endpoint controls separately; legacy /uploads remains Safety-1'});
 for(const mode of ['warm','repeat','cold'])for(const r of all[mode]){assert.ok(!JSON.stringify(r.trace).includes('B-private-'));assert.ok(!JSON.stringify(r).includes('B_SECRET_'));}
 // Authenticated protected-image endpoint cross-owner denial. Do not probe legacy raw uploads.
 const media='/api/ql/pieces/B-private-B01/photos/B-secret-photo-B01-ref-0';const denied=await fetch(s.base+media,{headers:{Authorization:'Bearer '+s.token('A')}});assert.equal(denied.status,404);save('protected-media.json',{crossOwnerStatus:denied.status,rawUploadsHardening:'deferred Safety-1'});
 const features=s.db.prepare("SELECT pp.id,pp.phash,pp.avg_color FROM piece_photos pp JOIN pieces p ON p.id=pp.piece_id WHERE p.user_id='A'").all();await rt.stop(s);s=null;
 s=await rt.start(false);rt.seed(s,corpus,manifest);for(const f of features)s.db.prepare('UPDATE piece_photos SET phash=?,avg_color=? WHERE id=?').run(f.phash,f.avg_color,f.id);
 for(const [i,q]of queries.entries()){const r=await rt.query(s,data(q));all.plain.push({...q,...r});if(i%100===0)console.log('plain',i);}
 await rt.stop(s);s=null;
 }finally{if(s)await rt.stop(s);}
 if(frozen)assert.deepEqual(all.plain.map(r=>[r.id,r.sha256,r.ranking]),frozen.map(r=>[r.id,r.sha256,r.ranking]),'Frozen baseline ranking/score differs across runs or environments');
 const differences=[];for(let i=0;i<queries.length;i++)for(const mode of ['repeat','plain'])if(JSON.stringify(all.warm[i].ranking)!==JSON.stringify(all[mode][i].ranking))differences.push({query:queries[i].id,mode});assert.deepEqual(differences,[],'unexplained ranking/score nondeterminism');
 const summary={version:1,parentCheckpoint:'7686bb32fd6475a2f870ef789eaafde09ff46d23',algorithmBaselineCheckpoint:'5fff6c4daf0b16de7f744fa541d8a94034b83f88',slice:'Features-1',serverSha256:sha(rt.source),fixtureSha256:sha(fs.readFileSync(path.join(corpus,'fixtures.json'))),querySha256:sha(fs.readFileSync(path.join(corpus,'queries.json'))),runtime:{node:process.version,sharp:require('sharp').versions,cpu:os.cpus()[0]?.model,platform:os.platform(),arch:os.arch()},coldProtocol:'Every query independently resets all 144 A feature pairs; four isolated loopback server/database shards, concurrent; instrumented timing is not a release latency gate',counts:{pieces:48,referenceImages:144,queries:516,positive:384,ambiguous:32,noMatch:100,privacyOnlyPieces:48,privacyOnlyReferences:144},cold:summarize(all.cold),warm:summarize(all.warm),plain:summarize(all.plain),determinism:{compared:1032,differences},multiPhoto:{rows:multi.length,differentFromFirst:multi.filter(r=>r.winningPhoto&&r.firstDisplayedPhoto&&r.winningPhoto!==r.firstDisplayedPhoto).length,matchingPhotoExposed:multi.some(r=>r.matchingPhotoExposed)},productionUntouched:true,testFlight49Unchanged:true};
 // Store compact rows and separate full observer traces, preserving reproducibility.
 for(const [mode,rows]of Object.entries(all)){save(mode+'-results.json',rows.map(({trace,...r})=>r));if(mode==='warm'||mode==='cold')save(mode+'-traces.json',rows.map(r=>({id:r.id,trace:r.trace?{...r.trace,candidates:r.trace.candidates.map(({piece_id,photo_id,score})=>({piece_id,photo_id,score})),winners:r.trace.winners.map(({piece_id,photo_id,score})=>({piece_id,photo_id,score}))}:null})));}
 save('summary.json',summary);save('cold-progression.json',progression);save('multi-photo.json',multi);save('gates.json',{accuracy:gates(require('../photo-eval/evidence/plain-results.json'),all.plain,{improvement:true,performance:false}),latency:'Paired same-machine comparison is required separately.'});
 const csv=['state,query,label,expected,top1,top1Score,correctRank,returned,latencyMs'];for(const mode of ['cold','warm','plain'])for(const r of all[mode]){const rank=r.ranking.findIndex(m=>r.expected.includes(m.id));csv.push([mode,r.id,r.label,r.expected.join('|'),r.ranking[0]?.id||'',r.ranking[0]?.score??'',rank<0?'':rank+1,r.ranking.length,r.ms].join(','));}fs.writeFileSync(path.join(out,'candidate.csv'),csv.join('\n')+'\n');
 const pct=x=>(x*100).toFixed(2)+'%',b=summary.plain,c=summary.cold;
 const rows=Object.entries(b.subsets).map(([k,v])=>`| ${k} | ${v.n} | ${pct(v.top1)} | ${pct(v.top3)} |`).join('\n');
 fs.writeFileSync(path.join(out,'REPORT.md'), '# Features-1 measured candidate\n\nSee summary.json for complete candidate metrics and README.md for scope. Frozen Eval-1 corpus and evidence are unchanged. Compare paired latency in same-machine.json.\n');console.log(JSON.stringify({counts:summary.counts,top1:b.positive.top1,top3:b.positive.top3,coldAbsent:c.positive.notEvaluated,latency:b.latencyMs}));return summary;}
module.exports={run};if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1});
